#!/usr/bin/python3
from function import factorize
import sys

def main(input_file):
    try:
        r = open(input_file, 'r')
        numbers = (int(line.strip()) for line in r)

        for number in numbers:
            results = factorize(number)
            for p, q in results:
                print(f"{number}={p}*{q}")
    except FileNotFoundError:
        print("Input file not found")
    except Exception as e:
        print("An error occured: {}".format(e))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <input_file>")

        sys.exit(1)
    else:
        input_file = sys.argv[1]
        main(input_file)

